version: '3.8'

services:
  # Caddy reverse proxy with SSL termination
  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

  # Your Node.js application
  nodejs-app:
    image: simple-nodejs-app:latest
    container_name: simple-nodejs-app
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - web

  # Existing Flask application
  flask-app:
    image: mo231993/lkdevbackend16:latest
    container_name: lk_dev_container
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge
