version: '3.8'

services:
  # Caddy reverse proxy with automatic SSL
  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

  # Your Node.js application
  nodejs-app:
    build: .
    container_name: simple-nodejs-app
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - web
    depends_on:
      - caddy

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge