name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Test application
      run: |
        # Start the app in background
        npm start &
        APP_PID=$!
        
        # Wait for app to start
        sleep 5
        
        # Test if app is responding
        curl -f http://localhost:3000 || exit 1
        
        # Clean up
        kill $APP_PID

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t simple-nodejs-app:latest .
        
    - name: Test Docker image
      run: |
        # Run container in background
        docker run -d -p 3001:3000 --name test-container simple-nodejs-app:latest
        
        # Wait for container to start
        sleep 10
        
        # Test if container is responding
        curl -f http://localhost:3001 || exit 1
        
        # Clean up
        docker stop test-container
        docker rm test-container
    
    - name: Build success
      run: echo "✅ Docker build and test completed successfully!"